### ISSUE TITLE
Couldn't open the FCMA Demo notebook file

### ISSUE THREAD

**Issue by yidawang** [peetal/FCMA_demo#2]
@peetal 

It says: Unreadable Notebook: /home/ubuntu/workspace/FCMA_demo/FCMA_demo.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...',)

One way may be clean the output before pushing to Github?

Thanks!

**Comment by peetal** [comment]
@yidawang  Sorry about that! Now it should be fixed. Many thanks!

**Comment by yidawang** [comment]
Thank you, it works now!

**Comment by peetal** [comment]
I have noticed that after I restored the notebook, some of the text documentations got lost. I have pushed a new version, now everything is up to date. Sorry for the confusion.
